### ISSUE TITLE
Port must be empty for ICMP tests.

### ISSUE THREAD

**Issue by Sraza11** [thousandeyes/terraform-provider-thousandeyes#101]
I am trying to create an ICMP test and get the following response. 

```
Error: Failed call API endpoint. HTTP response code: 400. Error: There were some errors in your request, please correct them before trying again. Error in field testId : Port must be empty for ICMP tests.
 ```

this is the config I am using for the test,  I have not defined any port for icmp test. 

resource "thousandeyes_agent_to_server" "example-tf-test" {
  test_name = "tf-test"
  interval = 120
  alerts_enabled = true
  description = "tf created test"
  server = "1.1.1.1"
  protocol = "ICMP"
  #enabled = false

  

  agents {
    agent_id = 03
  }
  
}

**Comment by sfreitas-te** [comment]
We are looking into this we will update during next week

**Comment by Sraza11** [comment]
Thank you for the update!  @sfreitas-te

**Comment by pedro-te** [comment]
@Sraza11 thank you for raising this to our attention!

[v1.1.1](https://github.com/thousandeyes/terraform-provider-thousandeyes/releases/tag/v1.1.1) was released to address this bug.

Can you try v1.1.1 and let us know if that fixes the issue for you?

**Comment by Sraza11** [comment]
v1.1.1 worked and did not prompt to provide a port number for the ICMP test.  👍 

Thank you!

**Comment by pedro-te** [comment]
Thank you for proving feedback @Sraza11 ! Much appreciated.
