### ISSUE TITLE
test with multi tag state issue

### ISSUE THREAD

**Issue by Sraza11** [thousandeyes/terraform-provider-thousandeyes#105]
even after applying the changes if I refresh the state (terraform plan), it updates the following attributes of the state.  Do I need to have groups in descending or ascending order? 

```
      ~ groups {
          ~ group_id = 421071 -> 122431
            # (1 unchanged attribute hidden)
        }
      ~ groups {
          ~ group_id = 122431 -> 421071
            # (1 unchanged attribute hidden)
        }

        # (1 unchanged block hidden)
    }
```

**Comment by Sraza11** [comment]
after upgrading the provider to 1.1.1, the tests with tags are not persisting.  even after applying the changes refresh in the plan indicates the value of the tag will be updated.  

as if the state file is not persisting?  did anyone look into this issue? @sfreitas-te

**Comment by pedro-te** [comment]
Thanks for raising this to our attention @Sraza11 ! We will look into this

**Comment by Sraza11** [comment]
thank you for the quick response!  @pedro-te

**Comment by pedro-te** [comment]
> thank you for the quick response! @pedro-te

I was able to reproduce the issue locally, we will work on fixing this

**Comment by Sraza11** [comment]
thank you @pedro-te .  looking fwd to the fix.

**Comment by Sraza11** [comment]
I also noticed when I run terraform plan I am seeing some extra letters at the end (â”€â”€â) @pedro-te 


Plan: 0 to add, 25 to change, 0 to destroy.

â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

**Comment by bgriffinte** [comment]
The extra letters at the end are mojibake (broken character encoding). That's UTF-8 encoded box drawing U+2500 light horizontal line rendered in I guess ISO-8859-1.

**Comment by Sraza11** [comment]
I do not have any horizontal lines or box drawings in my .tf file.  any idea how can I get rid of this mojibake?

**Comment by bgriffinte** [comment]
Not sure where that is coming from. Plans I run show things like 

```
Plan: 11 to add, 12 to change, 13 to destroy.

------------------------------------------------------------------------
```
Where the line is made of ordinary ASCII hyphens. Looks like something has tried to be fancier and failed.

**Comment by Sraza11** [comment]
So looks like (-----) is generated by the provider, not something that is part of tf config file.  I think something is wrong with the provider that it is adding mojibake ad the end of the plan. 

thanks @bgriffinte 



> Not sure where that is coming from. Plans I run show things like
> 
> ```
> Plan: 11 to add, 12 to change, 13 to destroy.
> 
> ------------------------------------------------------------------------
> ```
> 
> Where the line is made of ordinary ASCII hyphens. Looks like something has tried to be fancier and failed.

**Comment by pedro-te** [comment]
> So looks like (-----) is generated by the provider, not something that is part of tf config file. I think something is wrong with the provider that it is adding mojibake ad the end of the plan.
> 
> thanks @bgriffinte
> 
> > Not sure where that is coming from. Plans I run show things like
> > ```
> > Plan: 11 to add, 12 to change, 13 to destroy.
> > 
> > ------------------------------------------------------------------------
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Where the line is made of ordinary ASCII hyphens. Looks like something has tried to be fancier and failed.

@Sraza11 I'm unable to reproduce the weird characters you are seeing, plans look clean to me. In any case, I would suggest we discuss this in a separate issue, as this issue is about the `groups` field. I have a fix for the `groups` field on the way.

**Comment by Sraza11** [comment]
thank you @pedro-te.  I will open a new issue for mojibake

**Comment by pedro-te** [comment]
[v1.1.2](https://github.com/thousandeyes/terraform-provider-thousandeyes/releases/tag/v1.1.2) has been released which should address this issue.

@Sraza11 can I ask you to give that version a try, please?
