### ISSUE TITLE
Resource thousandeyes_label apply ends with Error: Failed call API endpoint. HTTP response code: 403. Error: 403 Forbidden

### ISSUE THREAD

**Issue by mbechc** [thousandeyes/terraform-provider-thousandeyes#124]
Snippet of configuration, many different approaches tried.

resource "thousandeyes_label" "vpn_underlay" {
  name = "vpn_underlay"
  type = "tests"
 
  tests {
    test_name = "cph_customer_overlay"
    agents {
      agent_id = data.thousandeyes_agent.underlay.agent_id
    }
  }
}

**Comment by pedro-te** [comment]
Apologies for the time it took us to address this. This should be fixed in the new version of the provider: 
https://github.com/thousandeyes/terraform-provider-thousandeyes/releases/tag/v2.0.0

Please give it a try and let us know if you're still facing these issues
