### ISSUE TITLE
Creating tests w/ account groups is not supported

### ISSUE THREAD

**Issue by johntdyer** [thousandeyes/terraform-provider-thousandeyes#33]
account groups are supported in the underlying library but not exposes in the provider.  We should fix that since we share tests within my org

**Comment by johntdyer** [comment]
https://github.com/william20111/go-thousandeyes/blob/adf85eb0c0732e5803cb9f525d536d4f05df4dd3/account_groups.go

**Comment by raul-te** [comment]
Thank you for reporting this issue. This feature is fully working since #95 was merged. It's documented [here](https://github.com/thousandeyes/terraform-provider-thousandeyes/blob/27074ab/docs/data-sources/account_group.md).
