### ISSUE TITLE
Adopting Maintenance and Bringing the Project to a Verified Provider State

### ISSUE THREAD

**Issue by tduzan-te** [thousandeyes/terraform-provider-thousandeyes#61]
Howdy @william20111,

I am a Product Manager at ThousandEyes, and I would like to thank you for building the Go SDK and Terraform provider for the ThousandEyes API to automate test creation.  Contributions like these help the customer community for ThousandEyes considerably.

It is our intention to build on top of your work and make updates and contributions to expand the capabilities of the provider, to bring it up to date with our upcoming v7 API, and to generally get it to a state to become a verified provider in the Terraform registry.  In that vein, we’d like to open a dialogue about adopting maintenance of this project with our engineering team, while continuing to accept community contributions.

Would you be open to having a conversation with me about this?

Thanks,

Tyler Duzan

**Comment by william20111** [comment]
Yes sounds great. Not getting the time i was before to maintain this in my new role, would be great to see this as a verified provider.

**Comment by tduzan-te** [comment]
Howdy William,

Thanks for replying so quickly.  If you'd like to chat before moving forward, I'm happy to meet.  I think probably the best path to make the transition would be to move the repositories into the ThousandEyes organization on Github.  We are building out a team we're calling API Engineering specifically to focus on maintaining SDKs and integrations like this, so we are intending to continue maintenance of both the provider and the Go SDK.

Let me know if that works for you, or if you'd like to meet to discuss?

Thanks!

**Comment by william20111** [comment]
Ah that sounds really good & all sounds sensible 👍 

> I think probably the best path to make the transition would be to move the repositories into the ThousandEyes organization on Github

How can I go about doing this?

**Comment by tduzan-te** [comment]
Howdy William,

I have a call with our team tomorrow to see how we can facilitate the change.  It looks like it may require temporarily adding you into the ThousandEyes organization or adding one our GH organization admins to this project as an admin first.  https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository indicates it's relatively straightforward other than the permissions issues.

I'll update this issue with more information tomorrow afternoon CST.

Thanks!

**Comment by tduzan-te** [comment]
Howdy @william20111,

So after discussions with the team and our IT security folks, they've suggested the right path for us to do this is to have you transfer this repository and the Go SDK to @raul-te who is the primary developer working on this project internally right now, and since he is already a member of the ThousandEyes organization on Github he can then successfully transfer it into the organization.  This way Github automatically redirects correctly and all the collaborators are maintained.

Let me know if you have any questions.

Thanks!

**Comment by william20111** [comment]
![Screenshot 2022-05-06 at 09 21 12](https://user-images.githubusercontent.com/3274971/167094799-e171c2e8-e9cf-4730-8283-b3e883db0e64.png)

might have to delete his fork?

**Comment by raul-te** [comment]
Hi William,

Glad to e-meet you! Thank you for your comprehensive work on the provider.

I've just deleted my repo `raul-te/terraform-provider-thousandeyes`, so you should be good to go. Apologies for the back and forth.

Thanks

**Comment by william20111** [comment]
Should have a request to transfer both 👍

**Comment by raul-te** [comment]
Thanks @william20111. I've accepted the request for both repositories. I'll proceed to transfer them to the `thousandeyes` organization.

**Comment by raul-te** [comment]
The provider is now maintained by ThousandEyes, and it's marked as `Verified` in the Terraform registry. We can consider this issue resolved. Thanks to everyone involved!
