### ISSUE TITLE
 Get "https://api.thousandeyes.com/v6/agents.json": Internal Server Error

### ISSUE THREAD

**Issue by richwats** [thousandeyes/terraform-provider-thousandeyes#63]
Hi, I've used this provider in the past to configure basic HTTP tests.  I'm now hitting a problem where I can't seem to create a data source for a cloud agent.   I now get a "Internal Server Error".     Happy to share the full plan separately.

```hcl
provider "thousandeyes" {
  token = var.te_token # Passed from Workspace Variable
}

data "thousandeyes_agent" "test" {
  agent_name = "Sydney, Australia"
}
```

```
Error: Get "https://api.thousandeyes.com/v6/agents.json": Internal Server Error
with module.fso.module.thousandeyes[0].data.thousandeyes_agent.test
on .terraform/modules/fso/modules/thousandeyes/main.tf line 21, in data "thousandeyes_agent" "test":
```

**Comment by raul-te** [comment]
Hi @richwats, and thanks for reaching out.

I've tried reproducing your use-case unsuccessfully as the plan works well for me. What version of the module are you using? Does it happen consistently on your retries? Having the full plan might help.

**Comment by richwats** [comment]
Hi Raul,

Apologies – I did track this down yesterday and it is my problem.   I’m using Terraform Cloud where the plan is itself executed from a remote cloud agent (Intersight Service for Terraform to be specific) – but I had forgotten to put the thousandeyes URL in the proxy exception list, basically the cloud agent couldn’t get to api.thousandeyes.com.

I’ll test again today and confirm but I’m happy to close this.

Thank you,
Richard

From: Raul Benencia ***@***.***>
Date: Friday, 27 May 2022 at 7:40 am
To: thousandeyes/terraform-provider-thousandeyes ***@***.***>
Cc: Richard Watson (richwats) ***@***.***>, Mention ***@***.***>
Subject: Re: [thousandeyes/terraform-provider-thousandeyes] Get "https://api.thousandeyes.com/v6/agents.json": Internal Server Error (Issue #63)

Hi @richwats<https://github.com/richwats>, and thanks for reaching out.

I've tried reproducing your use-case unsuccessfully as the plan works well for me. What version of the module are you using? Does it happen consistently on your retries? Having the full plan might help.
