### ISSUE TITLE
thousandeyes_http_server returns 400 when specifying alert_rules

### ISSUE THREAD

**Issue by Saffron-City** [thousandeyes/terraform-provider-thousandeyes#73]
I am getting 400 errors when creating/updating a `thousandeyes_http_server` resource with `alerts_enabled` set to true and `alert_rules` specified or unspecified

## Terraform and provider version
```
Terraform: 0.13.7 and 1.1.7
Provider: thousandeyes/thousandeyes version 1.0.0-alpha.3
```

## Expected behavior
thousandeyes_http_server resources are successfully created/updated when specifying alert rules via alert rule ID
## Actual behavior
Setting `alerts_enabled` to true and specifying an `alert_rule` block with a valid rule ID results in `Error: Failed call API endpoint. HTTP response code: 400. Error: &{0xc000228c10}`

## What works:
When alerts_enabled is set to false with no alert_rules specified, this creates the resource as expected:
```
resource "thousandeyes_http_server" "example" {
  test_name      = "tf test"
  interval       = 3600
  alerts_enabled = false
  url            = "redacted-url"

  agents {
    agent_id = 69
  }
}
```
## What doesn't work:
Simply setting alerts_enabled to true returns a 400. I'd expect this to use the default alert rules in this case based on the [wording in the documentation](https://registry.terraform.io/providers/thousandeyes/thousandeyes/latest/docs/resources/http_server#alert_rules)

Manually setting the alert rules in the web UI and updating the Terraform code accordingly reports no changes: `Apply complete! Resources: 0 added, 0 changed, 0 destroyed.`
```
resource "thousandeyes_http_server" "example" {
  test_name      = "tf test"
  interval       = 3600
  alerts_enabled = false
  url            = "redacted-url"

  agents {
    agent_id = 69
  }

  alert_rules {
    rule_id = 4795258
  }
  alert_rules {
    rule_id = 4795254
  }
}
```
Removing one of the alert_rules also returns a 400:
```
resource "thousandeyes_http_server" "example" {
  test_name      = "test"
  interval       = 3600
  alerts_enabled = false
  url            = "redacted-url"

  agents {
    agent_id = 69
  }

  alert_rules {
    rule_id = 4795258
  }
}
```

The plan shows only the following change:
```
      - alert_rules {
          - alert_rule_id             = 0 -> null
          - default                   = 0 -> null
          - include_covered_prefixes  = 0 -> null
          - minimum_sources           = 0 -> null
          - minimum_sources_pct       = 0 -> null
          - notify_on_clear           = 0 -> null
          - rounds_violating_out_of   = 0 -> null
          - rounds_violating_required = 0 -> null
          - rule_id                   = 4795254 -> null
          - test_ids                  = [] -> null
        }
```
The apply fails with the following error: `Error: Failed call API endpoint. HTTP response code: 400. Error: &{0xc000228c10}`

Please let me know if there's other relevant information I can provide to help with this.

**Comment by raul-te** [comment]
Thanks for reporting this issue, @Saffron-City. I a have a fix underway and will open a pull request shortly.
