### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by william20111** [thousandeyes/terraform-provider-thousandeyes#8]
## What

* Create full docs for each supported resource & data source

## Why

* Easier consumption of the tool when there is proper documentation for engineers to consume

## References

* Jfrog [docs][1] are pretty good should aim to look similar

[1]: https://github.com/atlassian/terraform-provider-artifactory/tree/master/website

**Comment by raul-te** [comment]
#79, #87 and #97 include the required documentation. We can consider this issue resolved.
